computation_hist/common.py

Fixed an issue where filepaths would only work on Unix machines. The OCR methods should also work on Windows now!
Additionally, there was an error in the process that created PDFs up to 7x larger than the original, which has now been fixed.

OCR Compatibility and Resize Fixes

---

djweb/dj_comp_hist/models.py

Document.file_name uniquely identifies a Document. We can use this to prevent duplicates when running populate_from_metadata multiple times w/o flushing the db before.

Made Document.file_name unique

---

djweb/templates/base.jinja2

directs to search_results instead of displaying error page (temp fix until we decide on what we want to do with the advanced search link or to have it at all)

advanced search link in navbar 

---

.gitignore

node_modules and package-lock.json should rarely be committed to a repository (it's like the virtual-env for javascript)

Minor change to .gitignore for js dev

---

djweb/dj_comp_hist/metadata_parser.py

Figured out with @Mayowa99 . Import should work now on Windows

Open documents specifically with utf8 (windows default is cp1252)

---

djweb/dj_comp_hist/views.py

The previous implementation of  the full text search returned a RawQuerySet, which doesn't work with the QuerySet that the other parts of the search expects. This commit fixes the issue (i.e. the full text search returns a query set).
Branch can be deleted after merge.

Fixed full text search error

---

.travis.yml
apps/archives/management/commands/populate_from_metadata.py

- Adds .travis.yml, which just installs the site and checks that populate_from_metadata runs without crashing
- make populate_from_metadata into a management command, so you can `python manage.py populate_from_metadata`

Travis setup

---

.travis.yml
requirements.txt

Latest version of Django does not play nice with sqlite3 < 3.8.2 (https://code.djangoproject.com/ticket/30055) -- but Travis comes by default with 3.8.2.
We resolve this here by coercing the installation of Django 2.1, so we don't get the version that chokes on 3.8.1. This is __not__ a good long-term solution.

Travis sqlite3 fix

---

templates/archives/advanced_search.jinja2

Displays "there are no documents that match your search" instead of nothing if there are no results

Add message to advanced_search.jinja2 when no results

---

.travis.yml

We no longer run Travis on all pushed branches: only pushes to master, PRs, and branches whose name contains the substring `travis` (case insensitive).

Travis branch config

---

static/css/styles.css
templates/base.jinja2

Fixes the footer so the images resize nicely and we don't take over the whole screen.
@Mayowa99 — could you please check out what I've done here? Your original solution was good for the case of a small sized screen, but because of the relative positioning and high top, you'd end up with the footer bar up above the bottom of the viewport in some situations. This new version keeps it fixed absolutely to the bottom, but also keeps it from stacking and just shrinks the images instead.

fix footer height and position

---

templates/archives/box.jinja2
templates/archives/browse.jinja2
templates/archives/doc.jinja2
templates/archives/folder.jinja2
templates/archives/list.jinja2
templates/archives/organization.jinja2
templates/archives/person.jinja2
templates/base.jinja2
templates/simulations/index.jinja2
z_unused/page.jinja2

```
{% block header %}
<h1>
"a page name"
</h1>
{% endblock %}
```
This is redundant so I got rid of occurances of this.

Getting rid of redundant <h1> tags

---

templates/archives/advanced_search.jinja2

I realized there are some names that contain "_".  I removed these underscores from the names to create a more readable display.
Instead of "Phillip M._Morse", this corrects it to "Phillip M. Morse".
Also I added colons to "Date" "Author" "Recipient" "Folder" that are being displayed underneath the document name. Again, this is for readability purposes.
This helps fix some issues in issue #310

Helps fix display issues in Advanced search 

---

templates/archives/advanced_search.jinja2

When we have the name of the different documents displayed, the information underneath it would be better organized if we had Author and Recipient in the same column. Also, Folder and Date in the same column. Author and Recipient is a pair and so is Folder and Date.
Helps solve some of the problems in #310

Switches order in document display

---

apps/archives/urls.py
templates/archives/folder.jinja2
templates/archives/organization.jinja2
templates/archives/person.jinja2
templates/archives/search_results.jinja2
templates/archives/stories/women_in_symbols.jinja2

This PR removes references to documents by PK and the associated urlpattern. Moving forward, we only reference documents by slug, as those will persist, whereas PKs might change depending on the import process from our metadata spreadsheet to the database.
@mgallegos3015 — I've requested your review, as yours was the one story where I replaced existing PK references to docs with slugs. Could you double check that the links in your story are still correct? I'm going to go ahead and merge in, but let me know if there's a problem there.

Reference documents by slug only, not by PK

---

apps/archives/models.py
apps/archives/views.py
templates/archives/list.jinja2

(... and remove sort filter from archives/list.jinja template, which was masking backend sorting)

add default ordering to some archive models

---

utilities/name_parser.py

Without this fix, we get both "Wiesner, J. B." and "Wiesner, J. b." because the original first name "J.B." is capitalized to "J.b." 
By moving the capitalization after the regex, this is fixed.

Moved capitalize statement to fix bug

---

apps/archives/views.py
templates/archives/browse.jinja2

First names used to ackwardly show up at the top of the persons list. Now the last name of that person is set to "Unknown" and is sorted into the unknown  section of the list.

Fixed names on list/person and remade "browse" to be more informative

---

templates/archives/doc.jinja2

Fixes issues with pdfjs clobbering the javascript on the documents page: it wasn't PDF.js's fault... I just forgot to close the iframe!

add closing iframe tag for pdf viewer

---

apps/archives/views.py
templates/archives/doc.jinja2
utilities/common.py
utilities/jinja_functions.py

Because we were using Path objects to generate aws urls for the pdfs, they were a bit malformed (single slashes instead of double), which was causing MS Edge to choke when embedding.
@Carol217 - could you double check that this works?

fix aws urls in get_file_path so that ms edge can understand them
