dhmit/computation_hist

- important_info/README.md
- important_info/tesseract.md
- requirements.txt
Added two new requirements (pytesseract and Wand) that will be used to convert Acrobat PDFs into searchable PDFs using Tesseract.
common.py will be updated hopefully soon
important_info is a file that can house markdown files of how-to's and other important information for other members of the lab should they need access to it.
> Added package requirements and important_info

- History Group/Principal Biographies.md
- History Group/Public Perception.md
Added a markdown to put principal biographies in when they're done and fixed a typo in Public Perception.md
> Added biographies markdown, fixed typo

- computation_hist/common.py
- requirements.txt
Added OCR methods and updated requirements list to reflect proper methods.
Unfortunately, the current workflow is rather slow, but it uses pytesseract to convert a given PDF to one embedded with proper OCR, a text file, or both depending on the method selected.
I will try to play with it some more to get it to be faster, but I wanted to make sure I got something up before the break.
> OCR Methods

- History Group/Hidden Figures Biographies.md
I created a markdown document for the biographies featuring hidden figures who were involved with the MIT Computation Center. Currently, I am working on writing a biography for Edna Tamm.
> Add markdown file for hidden figures biographies

- js_dev/whirlwind.html
- js_dev/whirlwind.js
These files include a deciaml to binary converter with some information about the Whirlwind computer. There are plans to add a core memory simulation and more whirlwind information.
> First Whirlwind Push

- computation_hist/common.py
Updated common.py such that the OCR methods now use pathlib.Path instead of os.path.
Additionally, moved around the functionality of the methods to provide more functionality.
> pathlib.Path and streamlining

- History Group/Hidden Figures.md
- computation_hist/documentation/Managing Editor and Oral History.md
Added markdown files for a writeup of my position and a place to put hidden figure biographies
> Added final writeup and hidden figures

- djweb/dj_comp_hist/models.py
- djweb/dj_comp_hist/templates/person.html
- djweb/dj_comp_hist/views.py
There was an issue with the existing template as some of the attribute names had been changed so it kept throwing an error.
> Fixing the template

- djweb/dj_comp_hist/models.py
- djweb/dj_comp_hist/templates/folder.html
- djweb/dj_comp_hist/templates/index.html
- djweb/dj_comp_hist/templates/list.html
- djweb/dj_comp_hist/templates/organization.html
- djweb/dj_comp_hist/urls.py
- djweb/dj_comp_hist/views.py
Added list, organizations, and folders.
> Added various views

- djweb/dj_comp_hist/templates/index.html
- djweb/dj_comp_hist/templates/list.html
- djweb/dj_comp_hist/urls.py
- djweb/dj_comp_hist/views.py
list.html is implimmented and now displays all model objects of a certain model.
> Made list.html

- djweb/dj_comp_hist/templates/base.jinja2
- djweb/dj_comp_hist/templates/box.jinja2
- djweb/dj_comp_hist/templates/folder.jinja2
- djweb/dj_comp_hist/templates/index.jinja2
- djweb/dj_comp_hist/templates/list.jinja2
- djweb/dj_comp_hist/templates/organization.jinja2
- djweb/dj_comp_hist/templates/person.jinja2
- djweb/dj_comp_hist/views.py
- djweb/djweb/jinja_functions.py
- djweb/djweb/jinja_utils.py
- djweb/djweb/settings.py
- requirements.txt
Jinja2 allows for writing templates that (a) look more like python and (b) are a lot more powerful.
> Backend changed to Jinja2

- djweb/dj_comp_hist/templates/base.html
Creating bootstrap in base.html
> Adding boostrap

- djweb/dj_comp_hist/templates/base.html
- djweb/dj_comp_hist/templates/search_results.jinja2
- djweb/dj_comp_hist/urls.py
- djweb/dj_comp_hist/views.py
Creating a search bar that searches by last name, folder name and document title
> Creating a pull request

- djweb/dj_comp_hist/templates/base.jinja2
- djweb/dj_comp_hist/templates/box.jinja2
- djweb/dj_comp_hist/templates/index.jinja2
- djweb/dj_comp_hist/views.py
> changed all base.html to base.jinja2

- djweb/dj_comp_hist/templates/base.jinja2
- djweb/dj_comp_hist/templates/search_results.jinja2
- djweb/dj_comp_hist/views.py
Correcting spelling mistakes
Allow for search of organization and by last name
> Improving nav-bar

- README.md
- new_developers.md
Work in progress
Co-Authored-By: Stephan Risi <srisi@users.noreply.github.com>
> New developer's guide

- djweb/dj_comp_hist/models.py
Cleaned up the models.py branch and hopefully didn't break anything.
> Code Cleanup

- djweb/dj_comp_hist/common.py
- djweb/dj_comp_hist/models.py
Pull request into keith-1, not master.
Really, if I want a change, why not implement it myself?
I commented out create_pages for the moment as I don't know what it does but `from .models import Document, Page` created a circular import (models imports from .common)
> Implemented my suggestion to change get_file_path

- computation_hist/data/aws_available_file.md
This has been on the sort_pdf branch for over a week. I think it's useful to have it in the main branch.
> Added currently available files on aws md

- djweb/dj_comp_hist/models.py
- djweb/dj_comp_hist/templates/list.jinja2
- djweb/dj_comp_hist/views.py
> tried to list models by attributes in place

- djweb/dj_comp_hist/models.py
- djweb/dj_comp_hist/templates/list.jinja2
- djweb/dj_comp_hist/views.py
Reverts dhmit/computation_hist#137
Reverted until the list function works properly
> Revert "tried to list models by attributes in place"

- djweb/templates/base.jinja2
My last pull request was not up to date with the style changes.
> Reimplement style changes

- djweb/dj_comp_hist/templates/index.jinja2
- djweb/templates/base.html
- djweb/templates/base.jinja2
archives dropdown menu makes a menu appear on leftside of screen rather than below button.
> fixed unresponsive collapsed drowndown menu/added style to base.jinja2

- djweb/templates/base.jinja2
Linked dropdown browse button to browse page and made the dropdown open directly below the button again
> Updated dropdown

- djweb/dj_comp_hist/metadata_parser.py
Sample search query (will return a set of documents):
`Document.objects.raw('SELECT * from doc_fts WHERE text MATCH "morse"')`
> Added full text search table to database

- djweb/dj_comp_hist/metadata_parser.py
- djweb/dj_comp_hist/views.py
Advanced search now works for phrases, but if you put a semicolon, it only searches what's before the semicolon
> Updated advanced search

- djweb/dj_comp_hist/templates/person.jinja2
> (Person page) Made the document names their own link

- docs_writeups_ideas_etc/new_developers/unboxing_django.md
- utilities/ocr.py
Minor changes to the paths used in ocr.py (doctest works again) and updated django unboxing tutorial
> Updated ocr.py paths and django unboxing tutorial

- .travis.yml
- requirements.txt
> Travis sqlite3 fix

- apps/archives/views.py
doing it through the right channels this time..
> removed bare excepts

- apps/archives/views.py
- utilities/metadata_parser.py
Full text search now works the same as the other search parameters.
> Changed full text search to not rely on sqlite3

- templates/archives/advanced_search.jinja2
- templates/base.jinja2
There is a block body which was redundant. I removed it.
> Getting rid of block body

- templates/archives/doc.jinja2
Updates to the document webpage so it matches the updated base file
> Document webpage

- apps/archives/views.py
- data/processed_pdfs/1_1_committee_on_machine_methods/docs/2/1_1_committee_on_machine_methods_2.txt
- docs_writeups_ideas_etc/writeups/Hidden Figures.md
- templates/archives/doc.jinja2
- utilities/common.py
- utilities/contribution_counter.py
- utilities/ocr.py
- utilities/sort_pdfs.py
- z_unused/document.py
Simple changes to code to improve readability
> pretty inconsequential lints

- apps/archives/views.py
- templates/archives/stories/README.md
Shows three random stories on the index page rather than all of them.
> show 3 random stories on index page

- apps/archives/urls.py
- apps/archives/views.py
- templates/archives/stories.jinja2
- templates/archives/story_card.jinja2
- templates/base.jinja2
- templates/index.jinja2
Adds a view that shows all of the stories and links to it in the main navbar.
> All stories page

- data/processed_pdfs/1_22_computation_center/docs/4/pages/2/1_22_computation_center_4_2.txt
Corrected OCR for page 2 of letter from Morse to Laura Hill; discusses 704 logic.
> Updated OCR: letter Morse->Laura Hill (1957, p.2)

- data/processed_pdfs/1_22_computation_center/docs/4/pages/1/1_22_computation_center_4_1.txt
Corrected OCR for handwritten letter: Morse to Laura (6 July 1957).
> Updated MS letter: Morse to "Laura" (1957)

- utilities/name_parser.py
e.g., 'McCormack' was getting changed to 'Mccormack' etc.
> fix our use of nameparser capitalize() to not squish mixed case names

- templates/archives/stories/time_records-teaser.jinja2
- templates/archives/stories/time_records.jinja2
Co-Authored-By: Felix Tran <felixtran39@users.noreply.github.com>
> Added missing article

- apps/archives/views.py
- templates/archives/list.jinja2
for browsing folders by box and number
> add box and folder number to list

- templates/archives/stories/women_in_symbols.jinja2
Additionally, I think since this article is all about hidden labor, we should recognize Lisa for her work as an editor.
> Fixed the slugs and made some other edits to Women in Symbols

- apps/archives/search.py
- static/css/search.css
- static/js/search.js
- templates/archives/search.jinja2
keyword search also operates as an "and" search but across multiple fields, "verzuh morse" now returns verzuh AND morse, rather than verzuh OR morse
> updated keyword search to accept exact phrases

- static/css/doc.css
- templates/archives/doc.jinja2
This can work as a bandaid until we find the formatting/placement that we want
> Added simple citation to doc pages

- static/css/styles.css
- templates/archives/about.jinja2
- templates/archives/story_card.jinja2
- templates/base.jinja2
The site should mostly look good on small screens now.
> css tweaks particularly for mobile display

- templates/archives/net_viz.jinja2
- templates/archives/timeline.jinja2
Panel-i-fy netviz and timeline for more consistent look through whole site
> Even more panels

- apps/archives/search.py
- templates/archives/story.jinja2
- templates/index.jinja2
- adds big search box on home page, with a bunch of sample searches
- makes keyword search into AND search by default for people
Please add better sample searches if you can think of any!
> add a big search box with sample searches to the homepage

- templates/archives/stories/digital_humanities.jinja2
Add link to letter about Cervantes -- pure DH...
> Add Cervantes letter

- templates/archives/stories/digital_humanities.jinja2
@Carol217 You're the author, right?
> Added author (Carol) to DH story

- templates/archives/stories/IBM_mechanics.jinja2
@montsegarza Do you prefer Montse or Montserrat?
> Added Montse as author

- static/css/simulations.css
- static/js/render.js
- templates/simulations/base.jinja2
> Align line numbers in simulations

- apps/archives/views.py
There weren't so many that it makes sense to have them rotate or disappear.
> Show all stories on front page of archive
